# Generated by Django 5.1 on 2024-09-07 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-datetime'], 'verbose_name': 'Transaction History', 'verbose_name_plural': 'Transaction Histories'},
        ),
        migrations.AlterField(
            model_name='history',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='history',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='history',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=10, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['user'], name='app_history_user_id_2b9ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['datetime'], name='app_history_datetim_256deb_idx'),
        ),
    ]
