# Generated by Django 5.1 on 2024-09-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_alter_history_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=10),
        ),
    ]
